Ruby Tic Tac Toe: Game testing
Temmarie/Tic-Tac-Toe pull request #11
Opened 2020-05-02 08:18 UTC by OA7

In this project we were asked to add specs for all public methods we created in the game, covering every edge cases.

2020-05-04 10:05 UTC, whiz25 requested changes
## Awesome :+1: 
You did a commendable job with this PR. All your tests pass very well. However, we need to add more test cases. We need every test block to have a positive and a negative scenario.
- [ ] add a test case for the display_board public method. All public methods must be tested.
- [ ] check my comments for more suggestions

### Martin Afani

2020-05-04 10:07 UTC, whiz25 commented on spec/games_spec.rb
> +    end
- test what happens if input is invalid and position is unavailable. Does the board update?

2020-05-04 21:02 UTC, Temmarie commented
We made the changes requested by the previous TSE which are : 
- adding a test case for all public methods and
- adding a negative test for update_board.

2020-05-05 20:33 UTC, mosesogwo approved these changes
**Hi team:clap: Good work:+1:. Project is approved**

Before you merge, add a negative test for your **#draw?** method just like you have done for **#update_board**

**Cheers:stars:**

### Status: Approved :heavy_check_mark:

2020-05-05 21:07 UTC, merged