Ruby Tic-Tac-Toe: Game_logic
Temmarie/Tic-Tac-Toe pull request #6
Opened 2020-04-28 13:26 UTC by Temmarie

In this third milestone, we were required to add real logic for our game, removing all inline comments used in the previous milestone. We have covered all edge cases, like :
- Asking the players if they'll like to restart the game,
- Alerting the players when they pick an already taken cell,
- Alerting the players when they input an invalid character.

2020-04-28 17:24 UTC, maelfosso requested changes
# Changes required :red_circle: 

Hello @Temmarie @OA7 
Everything is working :+1: Well job done !!
However, there are a few things you should change related to the SOLID principle.

Please, read the comments left below and make the suggested changes then submit a new code review request

Thanks
Mael FOSSO

2020-04-28 17:24 UTC, maelfosso commented on bin/main.rb
> +  end
**`[OPTIONAL]`** Can be asked once. So, please, could you move it out of that loop and just ask that at the beginning?

2020-04-28 17:24 UTC, maelfosso commented on bin/main.rb
> +          end
1. **Check** the input validity into a method from `Board` class
```ruby
def input_valid?(input)
...
return true/false
end
```

2. **Update the board** into the method from a `Board` class
```ruby
def update_board
@positions[inputs] = current_player.char
end
```

2020-04-28 17:24 UTC, maelfosso commented on bin/main.rb
> +      elsif board.positions.none?(Integer)
As a method, please.

2020-04-29 08:16 UTC, suretrust approved these changes
Hi team, 👋 

### Great job implementing the suggested changes. 🙌 Let's get this merged! 👍 

_Good luck with your future milestones and happy coding!_ 🎉

2020-04-29 08:19 UTC, merged